version: "3.9"

services:
  frontend:
    image: narainad308/pixamart-frontend:latest
    container_name: pixamart-frontend
    ports:
      - "3000:3000"  
    env_file:
      - .env  
    restart: always